/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package krpcj.fsw;

import java.io.IOException;
import java.util.Scanner;

import krpc.client.Connection;
import krpc.client.services.KRPC;
import krpcj.fsw.config.Constants;
import krpcj.fsw.data.Telemetry;
import krpcj.fsw.ui.InstrumentPanel;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class.getSimpleName());
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        logger.info(new App().getGreeting());

        Scanner scanner = new Scanner(System.in);
        boolean endProg = false;

        InstrumentPanel instrumentPanel = setupInstrumentPanel();
        Telemetry telemetry = new Telemetry();

        // Scan for input continuously until quit
        while (!endProg) {

            // Skip if no input
            if (!scanner.hasNext()) {
                continue;
            }

            // Skip if input is not an integer
            if (!scanner.hasNextInt()) {
                String input = scanner.next(); // Dequeue whatever character was provided
                logger.info("Disregarding: " + input);
                continue;
            }

            // Fetch integer
            int input = scanner.nextInt();
            logger.info("Input: " + input);
            switch (input) {
            case 0:
                endProg = true;
                break;
            case 1:
                logger.info("Connecting to KRPC server...");
                Connection conn = connectToServer();
                KRPC krpc = KRPC.newInstance(conn);
                logger.info(krpc.getStatus().getVersion());
                break;
            case 2:
                logger.info("Updating telemetry!");
                telemetry.setAirspeed(Math.random() * 160);
                telemetry.setPitch(Math.random() * 180 - 90);
                telemetry.setRoll(Math.random() * 360 - 180);
                instrumentPanel.updateTelem(telemetry);
                break;
            default:
                logger.info("Unrecognized input: " + input);
            }
        }
        scanner.close();
        instrumentPanel.closeWindow();
    }

    protected static Connection connectToServer() throws Exception {
        try {
            Connection conn = Connection.newInstance(Constants.CLIENT_NAME, Constants.SERVER_IP, Constants.SERVER_RPC_PORT, Constants.SERVER_STREAM_PORT);
            return conn;
        } catch (IOException e) {
            throw new Exception("No suitable KRPC server running! " + e.getMessage(), e);
        } catch (Exception e) {
            throw new Exception ("Unknown issue when connecting to server!" + e.getMessage(), e);
        }
    }

    protected static InstrumentPanel setupInstrumentPanel() {
        InstrumentPanel instrumentPanel = new InstrumentPanel();
        return instrumentPanel;
    }
}
